### ISSUE TITLE
Option to NOT include folders with matching search input

### ISSUE THREAD

**Issue by VikingAntics** [bruno-br/script-search#1]
Hi,

Love this extension!!  My single issue is that it matches all the files in a folder where the folder name includes the search input.  I would love to be able to disable the folder name part of the search matching and just show the files that match the search input.

The issue is when I search on a term "Weapon", it returns all the *.gd, and *.tres files in all of the folders with the word "Weapon" (i.e. WeaponSystems, Weapons, WeaponManager, etc) in the folder name and I just want to see the *.gd and *.tres files with the word "Weapon" in the file name.  Maybe I am doing something incorrectly, but that is the result I am seeing, so please forgive me if I'm doing something incorrectly.

I hope I explained this clearly.   This is similar to a Unity tool I used to use and it really speeds up coding without having to navigate to the folder to open a file constantly.   

P.S. It is still great to see the full path in the search results for those instances where files can have the same name in different folders.

Thank you for your consideration.

FWIW: I took a shot at the code and this is what I came up with.  It is probably cr@p code because I'm still learning GDScript and your code is so well organized and written, but maybe this will help, or you can make it better if you have the time.  It is not implemented as an "Configuration Option" to turn on/off "include folder names" which would be ideal.  I did add one more feature that the Unity tool had where you can filter on filetypes.  So you can type your search "weapon :gd", which would only show .gd files in the results or "weapon :png" would only show .png files.

Anyway, since I went through the effort, I figured I'd share it.  There is probably a better way to do this anyway.

<code>
func _file_name_matches_text(text: String, is_case_sensitive: bool) -> bool:
	var slice_array: PackedStringArray = self._file_name.split("/", false)
	var slice: String = slice_array[slice_array.size()-1].strip_edges()
	
	var filterText: String = text
	var filterIdx: int = filterText.rfind(":")
	var useTypeFilter: bool = filterIdx >= 0
	var filterStr: String = filterText.right(filterText.length() - filterIdx - 1)
	
	filterText = filterText.trim_suffix(":" + filterStr)
	
	if useTypeFilter:
		if is_case_sensitive: return slice.contains(filterText.strip_edges()) && slice.ends_with(filterStr)
		return slice.to_lower().contains(filterText.to_lower().strip_edges()) && slice.ends_with(filterStr)
	else:
		if is_case_sensitive: return slice.contains(text.strip_edges())
		return slice.to_lower().contains(text.to_lower().strip_edges())
</code>

**Comment by bruno-br** [comment]
Hi! Thanks for taking an interest in my extension, and for being so polite!

I really liked your suggestion, I can see how it could be useful to search for the file name only.

But I don't think it would be a good idea to put it as an option in the Configuration Menu, as it would be slow to switch on and off.

So I was thinking about using a symbol for file_name only searches, like the ":" character you suggested for extensions. For example:

- If you searched for "weapon", it would return all matching file_paths, even if only the directory name matches
- If you searched for ":weapon", it would return only the files with matching file name

That would make it easy to do both types of search without having to turn an option on and off in the ConfigMenu.

I was also planning on allowing multiple search terms. That would enable searching for file extensions easily:

- If you searched for ":weapon", it would return files with all of the allowed extensions
- If you searched for ":weapon .gd", it would return only the files that match both search texts.

What do you think?

**Comment by VikingAntics** [comment]
Thanks for responding so quickly.  I like your proposal.  I think it is a great solution and it provides all the features in an efficient interface.

I don't know if I would ever search on multiple terms for the way I use the extension, but I never thought of using it that way and in a big project, it may be very useful. Especially if I were searching for related files.

I could definitely see situations that I would use multiple extensions.  

Thank you for entertaining my requests!  I'm always hesitant to ask someone who is so generous with their IP and time for additional features. ;)

**Comment by bruno-br** [comment]
It's fine! Your suggestions seem simple, it shouldn't take long to implement.

Probably the best use case for the multiple terms search would be using the first term for a part of the file name and the second term for the extension. But for Godot projects you would probably just use .gd and .gdshader so maybe it wouldn't be that useful.

**Comment by bruno-br** [comment]
It's done! It was simpler than what I expected:

![image](https://github.com/bruno-br/script-search/assets/43356485/16c0df62-d4a5-4761-9ba1-739d58845cc3)

You can download from the `v1.2.0` branch to use it right now

**Comment by VikingAntics** [comment]
Awesome!! Thank you so much for adding these features!

**Comment by bruno-br** [comment]
You are welcome :)
